# Generated by Django 5.2.14 on 2026-05-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("doctor", "Bác sĩ"),
                    ("admin", "Quản trị viên"),
                    ("patient", "Bệnh nhân"),
                ],
                default="doctor",
                max_length=20,
            ),
        ),
    ]
