# Generated by Django 5.2.14 on 2026-05-23 18:05

import json
from pathlib import Path

import modeling.models
from django.conf import settings
from django.db import migrations, models


DEFAULT_RETRAIN_CONFIG = {
    "schedule": "1d",
    "min_new_labels": 100,
    "min_new_ratio": 0.10,
    "min_new_positives": 20,
    "min_positive_targets": 2,
    "min_days": 7,
    "urgent_new_labels": 500,
    "max_missing_rate": 0.05,
    "max_duplicate_rate": 0.30,
    "force": False,
}


def create_default_config(apps, schema_editor):
    AirflowRetrainConfig = apps.get_model("modeling", "AirflowRetrainConfig")
    AirflowRetrainConfig.objects.get_or_create(**DEFAULT_RETRAIN_CONFIG)
    config_path = Path(settings.BASE_DIR) / "configs" / "airflow_retrain_config.json"
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(json.dumps(DEFAULT_RETRAIN_CONFIG, indent=2) + "\n", encoding="utf-8")


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirflowRetrainConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        default="1d",
                        help_text="Cron: 0 2 * * *; Airflow preset: @daily; interval: 15m, 2h, 1d; or manual/none to disable automatic scheduling.",
                        max_length=64,
                        validators=[modeling.models.validate_retrain_schedule],
                    ),
                ),
                (
                    "min_new_labels",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Minimum new labeled records required before retraining.",
                    ),
                ),
                (
                    "min_new_ratio",
                    models.FloatField(
                        default=0.1,
                        help_text="Minimum new-label ratio compared with current training rows.",
                        validators=[modeling.models.validate_ratio],
                    ),
                ),
                (
                    "min_new_positives",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Minimum new positive labels required before retraining.",
                    ),
                ),
                (
                    "min_positive_targets",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Minimum number of target classes that must have positive labels.",
                    ),
                ),
                (
                    "min_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Minimum days between successful retraining runs.",
                    ),
                ),
                (
                    "urgent_new_labels",
                    models.PositiveIntegerField(
                        default=500,
                        help_text="New-label count that can bypass the minimum-days rule.",
                    ),
                ),
                (
                    "max_missing_rate",
                    models.FloatField(
                        default=0.05,
                        help_text="Maximum allowed missing-value rate in new training data.",
                        validators=[modeling.models.validate_ratio],
                    ),
                ),
                (
                    "max_duplicate_rate",
                    models.FloatField(
                        default=0.3,
                        help_text="Maximum allowed duplicate-record rate in new training data.",
                        validators=[modeling.models.validate_ratio],
                    ),
                ),
                (
                    "force",
                    models.BooleanField(
                        default=False,
                        help_text="Force retraining even when policy checks would skip it.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Airflow retrain config",
                "verbose_name_plural": "Airflow retrain config",
            },
        ),
        migrations.RunPython(create_default_config, migrations.RunPython.noop),
    ]
