# Generated by Django 5.2.14 on 2026-05-23 19:34

import json
from pathlib import Path

import modeling.models
from django.conf import settings
from django.db import migrations, models


DEFAULT_MODEL_TRAINING_CONFIG = {
    "tune": True,
    "n_trials": 5,
    "timeout": 600,
    "register": True,
    "promotion_metric": "f1_macro",
    "promotion_min_delta": 0.01,
    "force_promote": False,
    "log_optuna_trials": False,
    "enabled_models": ["logistic_regression", "random_forest"],
    "optuna": {"n_splits": 3, "random_state": 42},
    "search_space": modeling.models.default_search_space(),
}


def create_default_training_config(apps, schema_editor):
    ModelTrainingConfig = apps.get_model("modeling", "ModelTrainingConfig")
    ModelTrainingConfig.objects.get_or_create(**DEFAULT_MODEL_TRAINING_CONFIG)
    config_path = Path(settings.BASE_DIR) / "configs" / "model_training_config.json"
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(json.dumps(DEFAULT_MODEL_TRAINING_CONFIG, indent=2) + "\n", encoding="utf-8")


class Migration(migrations.Migration):

    dependencies = [
        ("modeling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelTrainingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tune",
                    models.BooleanField(
                        default=True,
                        help_text="Use Optuna to tune model hyperparameters.",
                    ),
                ),
                (
                    "n_trials",
                    models.PositiveIntegerField(
                        default=5, help_text="Number of Optuna trials per model family."
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        default=600,
                        help_text="Optuna timeout in seconds per model family.",
                    ),
                ),
                (
                    "register",
                    models.BooleanField(
                        default=True,
                        help_text="Register the promoted model in MLflow Model Registry.",
                    ),
                ),
                (
                    "promotion_metric",
                    models.CharField(
                        default="f1_macro",
                        help_text="Metric used to compare candidate model with champion.",
                        max_length=64,
                    ),
                ),
                (
                    "promotion_min_delta",
                    models.FloatField(
                        default=0.01,
                        help_text="Minimum metric improvement required to promote a candidate.",
                    ),
                ),
                (
                    "force_promote",
                    models.BooleanField(
                        default=False,
                        help_text="Promote candidate even when it is worse than champion.",
                    ),
                ),
                (
                    "log_optuna_trials",
                    models.BooleanField(
                        default=False,
                        help_text="Log each Optuna trial to MLflow. This creates many runs.",
                    ),
                ),
                (
                    "enabled_models",
                    models.JSONField(
                        default=modeling.models.default_enabled_models,
                        help_text='Model families to train, e.g. ["logistic_regression", "random_forest"].',
                    ),
                ),
                (
                    "optuna",
                    models.JSONField(
                        default=modeling.models.default_optuna_config,
                        help_text="Optuna and cross-validation settings.",
                    ),
                ),
                (
                    "search_space",
                    models.JSONField(
                        default=modeling.models.default_search_space,
                        help_text="Hyperparameter search spaces per model family.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Model training config",
                "verbose_name_plural": "Model training config",
            },
        ),
        migrations.RunPython(create_default_training_config, migrations.RunPython.noop),
    ]
