# Generated by Django 3.2.23 on 2026-05-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20260522_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='doctor_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
