apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Diabetes PostgreSQL
    uid: diabetes_postgres
    type: postgres
    access: proxy
    editable: true
    jsonData:
      database: ${PGDATABASE}
      sslmode: ${PGSSLMODE}
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: ${PGPASSWORD}
    user: ${PGUSER}
    url: ${PGHOST}:${PGPORT}
