apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Diabetes SQLite
    uid: diabetes_sqlite
    type: frser-sqlite-datasource
    editable: true
    jsonData:
      path: /var/lib/grafana/sqlite/db.sqlite3
