# Generated by Django 5.2.14 on 2026-05-14 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientTargetFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nep", models.BooleanField(default=False, verbose_name="Nephropathy")),
                ("neu", models.BooleanField(default=False, verbose_name="Neuropathy")),
                ("ret", models.BooleanField(default=False, verbose_name="Retinopathy")),
                (
                    "cv",
                    models.BooleanField(
                        default=False, verbose_name="Cardiovascular complication"
                    ),
                ),
                (
                    "per_vas",
                    models.BooleanField(
                        default=False, verbose_name="Peripheral Vascular complication"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_features",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
