# Generated by Django 5.2.14 on 2026-05-15 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patienttargetfeatures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patienttargetfeatures",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_features",
                to="patients.patient",
                unique=True,
            ),
        ),
    ]
