# Generated by Django 3.2.23 on 2026-05-15 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patienttargetfeatures"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("age", models.PositiveIntegerField()),
                ("sex", models.TextField()),
                ("bmi", models.FloatField()),
                ("sp", models.FloatField()),
                ("bp", models.FloatField()),
                ("hba1c", models.FloatField()),
                ("fps", models.FloatField()),
                ("pps", models.FloatField()),
                ("fam_ho", models.TextField()),
                ("on_age", models.FloatField()),
                ("dia_life", models.TextField()),
                ("smk", models.TextField()),
                ("phy_act", models.TextField()),
                ("med_use", models.TextField()),
                ("med_adh", models.TextField()),
                ("source", models.CharField(default="mock_his", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="clinical_records", to="patients.patient")),
            ],
        ),
    ]
