# Generated by Django 3.2.23 on 2026-05-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_patient_risk_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalRecordLabel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nep", models.BooleanField(default=False, verbose_name="Nephropathy")),
                ("neu", models.BooleanField(default=False, verbose_name="Neuropathy")),
                ("ret", models.BooleanField(default=False, verbose_name="Retinopathy")),
                ("cv", models.BooleanField(default=False, verbose_name="Cardiovascular complication")),
                ("per_vas", models.BooleanField(default=False, verbose_name="Peripheral Vascular complication")),
                ("source", models.CharField(default="mendeley_mock", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinical_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label",
                        to="patients.clinicalrecord",
                    ),
                ),
            ],
        ),
    ]
