# Generated by Django 5.2.14 on 2026-05-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0008_clinicalrecordlabel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinicalrecord",
            name="sex",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="age",
        ),
        migrations.DeleteModel(
            name="PatientRiskStatus",
        ),
    ]
